language: python
python: 3.4
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libhdf5-serial-dev
    - pip install numpy
    - pip install --install-option="--no-cython-compile" cython
    - pip install -r requirements.txt
    - python setup.py install
script:
    - py.test
